//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EmotionalAppraisalWF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EmotionalAppraisalWF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Belief.
        /// </summary>
        internal static string AddOrEditBeliefForm_AddOrEditBeliefForm_Edit_Belief {
            get {
                return ResourceManager.GetString("AddOrEditBeliefForm_AddOrEditBeliefForm_Edit_Belief", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string AddOrEditBeliefForm_AddOrEditBeliefForm_Update {
            get {
                return ResourceManager.GetString("AddOrEditBeliefForm_AddOrEditBeliefForm_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Belief already exists, use the edit function..
        /// </summary>
        internal static string BeliefAlreadyExistsExceptionMessage {
            get {
                return ResourceManager.GetString("BeliefAlreadyExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Appraisal Rule.
        /// </summary>
        internal static string EditAppraisalRuleFormTitle {
            get {
                return ResourceManager.GetString("EditAppraisalRuleFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Event Record.
        /// </summary>
        internal static string EditAutobiographicalEventFormTitle {
            get {
                return ResourceManager.GetString("EditAutobiographicalEventFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Condition.
        /// </summary>
        internal static string EditConditionEventFormTitle {
            get {
                return ResourceManager.GetString("EditConditionEventFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Emotion Disposition.
        /// </summary>
        internal static string EditEmotionDispositionFormTitle {
            get {
                return ResourceManager.GetString("EditEmotionDispositionFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Emotion.
        /// </summary>
        internal static string EditEmotionFormTitle {
            get {
                return ResourceManager.GetString("EditEmotionFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disposition already exists, use the edit function..
        /// </summary>
        internal static string EmotionDispositionAlreadyExistsExceptionMessage {
            get {
                return ResourceManager.GetString("EmotionDispositionAlreadyExistsExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &quot;Perspective&quot; cannot be an empty string.
        /// </summary>
        internal static string EmptyPerspectiveError {
            get {
                return ResourceManager.GetString("EmptyPerspectiveError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string ErrorDialogTitle {
            get {
                return ResourceManager.GetString("ErrorDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Decay.
        /// </summary>
        internal static string ErrorHalfLifeDecay {
            get {
                return ResourceManager.GetString("ErrorHalfLifeDecay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file.
        /// </summary>
        internal static string InvalidFileError {
            get {
                return ResourceManager.GetString("InvalidFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_gaips_rasterized {
            get {
                object obj = ResourceManager.GetObject("logo_gaips_rasterized", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emotional Appraisal Asset.
        /// </summary>
        internal static string MainFormPrincipalTitle {
            get {
                return ResourceManager.GetString("MainFormPrincipalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Field is required.
        /// </summary>
        internal static string RequiredFieldError {
            get {
                return ResourceManager.GetString("RequiredFieldError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string TitleSeparator {
            get {
                return ResourceManager.GetString("TitleSeparator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Defines how fast an emotion decays over time. The value is the actual time it takes a decay:1 emotion to reach half of its initial intensity..
        /// </summary>
        internal static string TooltipEmotionalHalflife {
            get {
                return ResourceManager.GetString("TooltipEmotionalHalflife", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save file..
        /// </summary>
        internal static string UnableToSaveFileError {
            get {
                return ResourceManager.GetString("UnableToSaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string UpdateButtonLabel {
            get {
                return ResourceManager.GetString("UpdateButtonLabel", resourceCulture);
            }
        }
    }
}
